feat(create-password): first time access before create account screen.
abiglobalhealth/proapp-rn pull request #24
Opened 2023-03-29 14:18 UTC by elenitaex5

# Description

First time access before create account screen has been added.
This flows has been tested and developed:
- Deep link with no token: redirect to login
- Expired token: shows message with expired activation link
- Token well formed: shows create account screen.

# Checklist:

- [X] Storybook has been updated (if needed) and still working
- [X] Tests have been run locally before create the PR

---

- [ ] Tested in Android simulator
- [ ] Tested in iOS simulator
- [ ] Tested in Android device through Expo Go
- [ ] Tested in Android device as app
- [ ] Tested in iOS device through Expo Go
- [ ] Tested in iOS device as app
- [ ] Tested in web

2023-03-30 21:09 UTC, elenitaex5 commented on App.tsx
> +  // enableNative: false,
I know is commented

2023-03-31 09:46 UTC, ylagef requested changes

2023-03-31 09:46 UTC, ylagef commented on src/contexts/AuthContext.tsx
> +    //   })
Needed?

2023-03-31 09:46 UTC, ylagef commented on src/helpers/axios-interceptors.ts
> +        error: error
```suggestion
        error
```

2023-03-31 09:46 UTC, ylagef commented on src/navigation/types.ts
> +  ActionFeedback: { status: ActionFeedbackStatus } | undefined
Is this the same?

```suggestion
  CreatePassword?: { token: string }
  ActionFeedback?: { status: ActionFeedbackStatus }
```

2023-03-31 09:46 UTC, ylagef commented on src/screens/CreatePassword/index.tsx
> +        return
Returns are not needed if they return void, right?

```suggestion
        }
```

2023-03-31 09:46 UTC, ylagef commented on src/screens/CreatePassword/index.tsx
> +        }
Maybe would be nice to have all this error codes moved to an enum in order to reuse it and avoid typos. Not required now, but recommended.

2023-03-31 09:46 UTC, ylagef commented on src/screens/CreatePassword/index.tsx
> +      )}
Duplicated same condition?

2023-03-31 09:51 UTC, elenitaex5 commented on src/contexts/AuthContext.tsx
> +    //   })
YES

2023-03-31 13:17 UTC, elenitaex5 commented on src/screens/CreatePassword/index.tsx
> +        return
right

2023-03-31 13:22 UTC, elenitaex5 commented on src/screens/CreatePassword/index.tsx
> +        }
done

2023-03-31 13:28 UTC, ylagef approved these changes

2023-04-03 09:33 UTC, ylagef reviewed
Check my comments

2023-04-03 09:33 UTC, ylagef commented on src/hooks/useCachedResources.ts
> +        // SplashScreen.hideAsync()
Can be removed?

2023-04-03 09:33 UTC, ylagef commented on src/screens/CreatePassword/index.tsx
> +        }
Is all ifs check the same variable a switch is better

2023-04-03 09:33 UTC, ylagef commented on src/screens/CreatePassword/index.tsx
> +        if (firstAccess?.newPasswordRequired === false) {
Why don't do this?

```suggestion
        if (!firstAccess?.newPasswordRequired) {
```

2023-04-03 10:31 UTC, elenitaex5 commented on src/hooks/useCachedResources.ts
> +        // SplashScreen.hideAsync()
yes

2023-04-03 10:51 UTC, merged