Feat(auth-refresh): [ABI-4920] Validate and refresh session
abiglobalhealth/proapp-rn pull request #27
Opened 2023-04-18 12:15 UTC by elenitaex5

# Description
Including new endpoint call `POST /auth/refresh` to validate and refresh session token.
Refresh token has been included in Auth Context and before doing any api call.
Including a dumb screen after being logged in 

# Checklist:

- [X] Storybook has been updated (if needed) and still working
- [X] Tests have been run locally before create the PR

---

- [X] Tested in Android simulator
- [X] Tested in iOS simulator
- [ ] Tested in Android device through Expo Go
- [ ] Tested in Android device as app
- [ ] Tested in iOS device through Expo Go
- [ ] Tested in iOS device as app
- [ ] Tested in web

2023-04-18 14:42 UTC, ylagef requested changes

2023-04-18 14:42 UTC, ylagef commented on src/helpers/axios-interceptors.ts
> +  return Object.keys(headers).indexOf('authorization') === -1
```suggestion
  return !Object.keys(headers).includes('authorization')
```

2023-04-19 07:27 UTC, elenitaex5 commented on src/helpers/axios-interceptors.ts
> +        }
No, I need it in the end after everything done before.

2023-04-19 07:53 UTC, ylagef approved these changes
LGTM 🎉

2023-04-21 11:18 UTC, merged